define([], function () {
  return {
    "PropertyPaneDescription": "Define PekaoQA settings",
    "WebConfigGroupName": "Data source config",
    "ListConfigGroupName": "List config",
    "ContentSourceType": "Content source type",
    "ListNameLabel": "List name",
    "SearchQueryLabel": "Search query",
    "SearchRowLimit": "Search row limit",
    "ContentSourceTypeLabel": "Content source type",
    "ContentSourceTypeLabelWeb": "Current web",
    "ContentSourceTypeLabelSearch": "Search service",
    "CategoryFieldLabel": "Category field",
    "OrderNoFieldLabel": "Order field",
    "QuestionFieldLabel": "Question field",
    "AnswerFieldLabel": "Answer field",
    "ActiveFieldLabel": "Active field",
    "DisplaySettingsGroupName": "Display settings",
    "PageLengthLabel": "Page length",
    "ShowSearchBoxLabel": "Show search box",
    "ShowSearchBoxLabelYes": "Show",
    "ShowSearchBoxLabelNo": "Hide",
    "FieldRequired": "This s required field",
    "ShowPagerLabel": "Show pager",
    "ShowPagerLabelYes": "Show",
    "ShowPagerLabelNo": "Hide",
    "ToggleGroupName": "Toggle settings",
    "ItmesExpandedLabel": "Items expanded",
    "ItmesExpandedLabelYes": "Expanded",
    "ItmesExpandedLabelNo": "Collapsed",
    "ToggleBehaviorAfterOpenLabel": "Behavior after open",
    "ToggleBehaviorAfterOpenLabelNo": "Leave remaining",
    "ToggleBehaviorAfterOpenLabelYes": "Close remaining",
    "CssStylesLabel": "CssStyles"
  }
});