define([], function () {
  return {
    "PropertyPaneDescription": "Zdefiniuj ustawienia PekaoQA",
    "WebConfigGroupName": "Konifiguracja źródła danych",
    "ListConfigGroupName": "Konifiguracja listy",
    "ListNameLabel": "Nazwa listy",
    "SearchQueryLabel": "Zapytanie wyszukiwania",
    "SearchRowLimit":"Limit zwracanych wierszy",
    "ContentSourceTypeLabel": "Źródło elementów",
    "ContentSourceTypeLabelWeb": "Bieżąca witryna",
    "ContentSourceTypeLabelSearch": "Usługa wyszukiwania",
    "CategoryFieldLabel": "Pole kategorii",
    "OrderNoFieldLabel": "Pole sortowania",
    "QuestionFieldLabel": "Pole pytania",
    "AnswerFieldLabel": "Pole odpowiedzi",
    "ActiveFieldLabel": "Pole aktywny",
    "DisplaySettingsGroupName": "Ustawienia wyświetlania",
    "PageLengthLabel": "Ilość elementów na stronie",
    "ShowSearchBoxLabel": "Pokaż pole wyszukiwania",
    "ShowSearchBoxLabelYes": "Pokaż",
    "ShowSearchBoxLabelNo": "Ukryj",
    "FieldRequired": "Pole nie może być puste",
    "ShowPagerLabel": "Pokaż stronnicowanie",
    "ShowPagerLabelYes": "Pokaż",
    "ShowPagerLabelNo": "Ukryj",
    "ToggleGroupName": "Ustawienia trybu zwijania",
    "ItmesExpandedLabel": "Domyślny widok",
    "ItmesExpandedLabelYes": "Rozwinięty",
    "ItmesExpandedLabelNo": "Zwinięty",
    "ToggleBehaviorAfterOpenLabel": "Zachowanie po otwarciu",
    "ToggleBehaviorAfterOpenLabelNo": "Pozostaw otwarte",
    "ToggleBehaviorAfterOpenLabelYes": "Zamknij pozostałe",
    "CssStylesLabel":"Style CSS"
  }
});